In [ ]:
# Exercise 1:  Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5 matrix.

In [1]:
import numpy as np

In [25]:
# Create a numpy array from 1 to 10 and reshape it to a 2x5 matrix
array = np.arange(1, 11).reshape(2, 5)
print("Output:\n", array)

Output:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
# Exercise 2:  Create a numpy array containing the numbers from 1 to 20,and then extract the elements between the 5th and 15th index

In [27]:
# Create a numpy array from 1 to 20 and extract elements between the 5th and 15th index
array = np.arange(1, 21)
extracted_elements = array[5:16]
print("Output:\n", extracted_elements)


Output:
 [ 6  7  8  9 10 11 12 13 14 15 16]


In [ ]:
#  Exercise 3:  Create a Pandas series with the following data: {'apples': 3, 'bananas': 2, 'oranges': 1}. Then, add a new item to the series with the key 'pears' and the value 4.


In [7]:
import pandas as pd

In [29]:
# Create a pandas series and add a new item
data = {'apples': 3, 'bananas': 2, 'oranges': 1}
series = pd.Series(data)
series['pears'] = 4
print("Output:\n", series)

Output:
 apples     3
bananas    2
oranges    1
pears      4
dtype: int64


In [ ]:
# Exercise 4:  Create a dataframe with the following columns: name, age, and gender. The dataframe should have 10 rows of data.

In [31]:
# Create a dataframe with name, age, and gender columns
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace', 'Hannah', 'Ian', 'Julia'],
    'age': [25, 30, 22, 35, 29, 40, 33, 27, 45, 31],
    'gender': ['F', 'M', 'M', 'M', 'F', 'M', 'F', 'F', 'M', 'F']
}
df = pd.DataFrame(data)
print("Output:\n", df)


Output:
       name  age gender
0    Alice   25      F
1      Bob   30      M
2  Charlie   22      M
3    David   35      M
4      Eva   29      F
5    Frank   40      M
6    Grace   33      F
7   Hannah   27      F
8      Ian   45      M
9    Julia   31      F


In [13]:
# Exercise 5:  Add a new column to the data frame created in question 1, called occupation. The values for this column should be Programmer, Manager, and Analyst, corresponding to the rows in the dataframe.

In [33]:
# Add a new column 'occupation'
df['occupation'] = ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 
                    'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']
print("Output:\n", df)


Output:
       name  age gender  occupation
0    Alice   25      F  Programmer
1      Bob   30      M     Manager
2  Charlie   22      M     Analyst
3    David   35      M  Programmer
4      Eva   29      F     Manager
5    Frank   40      M     Analyst
6    Grace   33      F  Programmer
7   Hannah   27      F     Manager
8      Ian   45      M     Analyst
9    Julia   31      F  Programmer


In [17]:
# Exercise 6:  Select the rows of the dataframe where the age is greater than or equal to 30. 


In [35]:
# Select rows where age >= 30
filtered_df = df[df['age'] >= 30]
print("Output:\n", filtered_df)


Output:
     name  age gender  occupation
1    Bob   30      M     Manager
3  David   35      M  Programmer
5  Frank   40      M     Analyst
6  Grace   33      F  Programmer
8    Ian   45      M     Analyst
9  Julia   31      F  Programmer


In [21]:
# Exercise 7:  Convert this dataframe to a csv file and read that csv file, finally display the contents.

In [37]:
# Save dataframe to a CSV file and read it back
df.to_csv('dataframe.csv', index=False)
read_df = pd.read_csv('dataframe.csv')
print("Output:\n", read_df)


Output:
       name  age gender  occupation
0    Alice   25      F  Programmer
1      Bob   30      M     Manager
2  Charlie   22      M     Analyst
3    David   35      M  Programmer
4      Eva   29      F     Manager
5    Frank   40      M     Analyst
6    Grace   33      F  Programmer
7   Hannah   27      F     Manager
8      Ian   45      M     Analyst
9    Julia   31      F  Programmer
